### ISSUE TITLE
Pass max_jobs as CLI argument

### ISSUE THREAD

**Issue by antonmyronyuk** [seedofjoy/darq#248]
Darq Worker can easily handle 10+ I/O-bound tasks at a time, but even 5 simultaneous CPU-bound tasks cause CPU throttling. So it is useful to have different workers with own limits for CPU-bound and I/O-bound tasks. The simplest way to reach this goal is to make ability to pass `max_jobs` as CLI-argument for worker.

**Comment by antonmyronyuk** [comment]
@seedofjoy I can resolve this, if you don't mind

**Comment by seedofjoy** [comment]
It would be nice, thank you

**Comment by seedofjoy** [comment]
Merged, thanks
